

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: beadtool-backend

  frontend:
    build:
      context: ./beadtool-frontend
    ports:
      - "3000:3000"
    container_name: beadtool-frontend
    depends_on:
      - backend
